### ISSUE TITLE
Donut i sektordiagram

### ISSUE THREAD

**Issue by eivindhammers** [noradno/noradplot#10]

**Comment by eivindhammers** [comment]
@einartornes: ggplot2 har ingen innebygget funksjon for donut-charts, men det er mulig vha en hack: https://r-graph-gallery.com/doughnut-plot.html

Kanskje den beste løsningen er å unngå dem helt? Treemap istedenfor? https://www.data-to-viz.com/caveat/pie.html

**Comment by einartornes** [comment]
Ja, den hacken ser fint ut. Jeg justerer pie chartene vi har, men enig i at det er best å unngå dem ja og heller bruke treemap.

**Comment by eivindhammers** [comment]
Kanskje vi kan lage en egen geom_donut?

fre. 24. mar. 2023 kl. 16:13 skrev einartornes ***@***.***>:

**Comment by einartornes** [comment]
> @einartornes: ggplot2 har ingen innebygget funksjon for donut-charts, men det er mulig vha en hack: https://r-graph-gallery.com/doughnut-plot.html
> 
> Kanskje den beste løsningen er å unngå dem helt? Treemap istedenfor? https://www.data-to-viz.com/caveat/pie.html

Jeg implementerte denne løsningen.

**Comment by einartornes** [comment]
> @einartornes: ggplot2 har ingen innebygget funksjon for donut-charts, men det er mulig vha en hack: https://r-graph-gallery.com/doughnut-plot.html
> 
> Kanskje den beste løsningen er å unngå dem helt? Treemap istedenfor? https://www.data-to-viz.com/caveat/pie.html

@eivindhammers jeg implementerer denne løsningen.
