### ISSUE TITLE
Feilmelding i ggnorad() i main og dev branch.

### ISSUE THREAD

**Issue by einartornes** [noradno/noradplot#8]
ggnorad()
Error in check_font_path(regular, "regular") : 
  font file not found for 'regular' type

**Comment by eivindhammers** [comment]
Problemet er at R ikke installerer siste versjon av pakken, og jeg vet ikke hvorfor. Kanskje den ikke bygger fra scratch? Har prøvd å velge `build = TRUE` og `source = TRUE` i `install_github`, men det fungerer fortsatt ikke.

**Comment by eivindhammers** [comment]
Jeg fant ut av det ene problemet: ettersom vi spesifiserer "version" i DESCRIPTION, må vi bumpe versjonsnummeret når vi oppdaterer pakken (tror jeg). Den installerer i hvert fall riktig versjon nå (0.2.0)

Men det fungerer fortsatt ikke, fordi det virker som `font_add` ikke kan bruke en nettadresse for å laste inn en font. Så jeg må skrive en funksjon som laster ned fontene først, og deretter adder dem.
